/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.leedarson.rest.services;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author ouxiaodong
 */
@javax.ws.rs.ApplicationPath("rest")
public class ApplicationConfig extends Application {

    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /**
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(com.leedarson.resource.rest.ResourcesService.class);
        resources.add(com.leedarson.rest.services.BugProjectService.class);
        resources.add(com.leedarson.rest.services.DocumentFQCService.class);
        resources.add(com.leedarson.rest.services.DocumentHeaderService.class);
        resources.add(com.leedarson.rest.services.DocumentLineService.class);
        resources.add(com.leedarson.rest.services.DocumentOQCService.class);
        resources.add(com.leedarson.rest.services.LoginService.class);
        resources.add(com.leedarson.rest.services.ProductionLineGroupService.class);
        resources.add(com.leedarson.rest.services.ProductionLineService.class);
        resources.add(com.leedarson.rest.services.QuestionbankService.class);
        resources.add(com.leedarson.rest.services.ResourceRecordService.class);
        resources.add(com.leedarson.rest.services.SoftwareinfoSerivce.class);
        resources.add(com.leedarson.rest.services.TablelistService.class);
        return resources;
    }
    
}
