/***************FQC***************/
--FQC头表
CREATE TABLE ADM_MES.DROID_FQC_DOCUMENT_HEADER (
	DOCUMENT_HEADER_ID VARCHAR2(1000) NOT NULL,--主键ID
	DOCUMENT_NUMBER VARCHAR2(30) NOT NULL,--检验批号
	CATEGORY VARCHAR(30) NOT NULL,--类别（特殊检验/一般检验）
	DOCUMENT_TYPE VARCHAR2(30) NOT NULL,--表单类型
	DOCUMENT_STATUS VARCHAR2(30) NOT NULL,--待检/归档
	--工厂
	WORK_ORDER_NUMBER VARCHAR2(250)--生产工单号
	--销售订单号
	--销售订单行项目
	--物料ID
	--物料长描述
	--生产部门
	--客户简称
	PROD_LINE_GROUP_DES VARCHAR2(250)--生产课别
	PROD_LINE_ID_DES VARCHAR2(250)--生产线别
	INSPECTION_AMOUNT VARCHAR2(250)--报检数量
	SAMPLING_AMOUNT VARCHAR2(250)--抽样数量
	SHIFT_CODE VARCHAR2(1)--班次
	INSPECTOR VARCHAR2(250)--检验员
	RESULT_CODE VARCHAR2(30)--判定结果
	ATTR1 VARCHAR2(1000),--ATTR1
	ATTR2 VARCHAR2(1000),--ATTR2
	ATTR3 VARCHAR2(1000),--ATTR3
	ATTR4 VARCHAR2(1000),--ATTR4
	ATTR5 VARCHAR2(1000),--ATTR5
	CREATED_BY NUMBER NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY NUMBER NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY (DOCUMENT_HEADER_ID)
)

--FQC项目检验行表
CREATE TABLE ADM_MES.DROID_FQC_DOCUMENT_LINE(

	DOCUMENT_LINE_ID NUMBER NOT NULL,--ID
	DOCUMENT_HEADER_ID NUMBER NOT NULL,
	LEVEL_1 NUMBER NOT NULL,
	LEVEL_2 NUMBER,
	LEVEL_3 NUMBER,
	OPTION_ID NUMBER NOT NULL,
	RESULT_CODE VARCHAR2(30) NOT NULL,
	RESULT_TEXT VARCHAR2(3000),
	ATTR1 VARCHAR2(1000),--ATTR1
	ATTR2 VARCHAR2(1000),--ATTR2
	ATTR3 VARCHAR2(1000),--ATTR3
	ATTR4 VARCHAR2(1000),--ATTR4
	ATTR5 VARCHAR2(1000),--ATTR5
	CREATED_BY NUMBER NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY NUMBER NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY (DOCUMENT_LINE_ID)

)

--缺陷记录头表
CREATE TABLE ADM_MES.DROID_FQC_BUG_HEADER (
	DOCUMENT_BUG_HEADER_ID VARCHAR2(1000) NOT NULL,--主键ID
	DOCUMENT_HEADER_ID VARCHAR2(1000) NOT NULL,--FQC头ID
	BUG_LEVEL VARCHAR2(30)--缺陷级别（CR/MA/MB/MI)
	SAMPLING_STANDARD VARCHAR2(100)--抽样标准(AQL)
	ACCPECT_VALUE VARCHAR2(30)--接受数值(AC)
	REJECT_VALUE VARCHAR2(30)--打回数值(RE)
	BUGS_AMOUNT VARCHAR2(30)--不良数汇总(SUM)
	RESULT_CODE VARCHAR2(30)--判定结果(默认OK)
	ATTR1 VARCHAR2(1000),--ATTR1
	ATTR2 VARCHAR2(1000),--ATTR2
	ATTR3 VARCHAR2(1000),--ATTR3
	ATTR4 VARCHAR2(1000),--ATTR4
	ATTR5 VARCHAR2(1000),--ATTR5
	CREATED_BY NUMBER NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY NUMBER NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY (DOCUMENT_BUG_HEADER_ID)
)
--缺陷检验行表
CREATE TABLE ADM_MES.DROID_FQC_BUG_LINE (
	DOCUMENT_BUG_LINE_ID VARCHAR2(1000) NOT NULL,--主键ID
	DOCUMENT_BUG_HEADER_ID VARCHAR2(1000) NOT NULL,--缺陷记录头ID
	BUG_CODEGRUPPE VARCHAR(250) NOT NULL,--缺陷代码组
	BUG_CODE VARCHAR(250) NOT NULL,--缺陷代码
	BUG_COUNT VARCHAR(250) NOT NULL,--缺陷数量
	ATTR1 VARCHAR2(1000),--ATTR1
	ATTR2 VARCHAR2(1000),--ATTR2
	ATTR3 VARCHAR2(1000),--ATTR3
	ATTR4 VARCHAR2(1000),--ATTR4
	ATTR5 VARCHAR2(1000),--ATTR5
	CREATED_BY NUMBER NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY NUMBER NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
	PRIMARY KEY (DOCUMENT_BUG_LINE_ID)
)

/*********************/
--缺陷题库表
CREATE TABLE ADM_MES.DROID_BUG_BANK (
	--主键id
	--一级题库类型
	--二级题库类型
	--不良代码
	--不良项目
	--缺陷等级
	ATTR1 VARCHAR2(1000),--ATTR1
	ATTR2 VARCHAR2(1000),--ATTR2
	ATTR3 VARCHAR2(1000),--ATTR3
	ATTR4 VARCHAR2(1000),--ATTR4
	ATTR5 VARCHAR2(1000),--ATTR5
	CREATED_BY VARCHAR2(1000) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	LAST_UPDATED_BY VARCHAR2(1000) NOT NULL,
	LAST_UPDATE_DATE DATE NOT NULL,
)
